{
 "title": "Otus Data Lab",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Mem Info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Active_anon_bytes" },
    { "expr": "go_memstats_sys_bytes" }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_network_carrier" },
    {
     "expr": "net_conntrack_dialer_conn_attempted_total"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"sda\"}"
    },
    {
     "expr": "node_disk_io_time_seconds_total"
    }
   ]
  },
  {
   "title": "CPU info",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_cpu_guest_seconds_total" },
    { "expr": "node_cpu_seconds_total" }
   ]
  }
 ]
}